In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

dotp = np.dot(x,y)
print(dotp)

mult = x*y
print(mult)

32
[ 4 10 18]


In [ ]:
# Sampling from a unifrom distribution

d = np.random.rand(3,3)
d<0.5

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

Average computer
---



In [ ]:
n_samples = 300
x = np.random.randint(-50, 50, n_samples)

input_shape = (3,1)
output_shape = (1,1)
batch_size = int(np.floor(n_samples/input_shape[0]))
X = x.reshape(-1, input_shape[0], input_shape[1])

Y = np.zeros((batch_size, output_shape[1]))
for i in range(batch_size - 2):
  Y[i,:] = np.mean(X[i,:,:])

In [ ]:
X[0,0,0]

-8

In [ ]:
X[0]

array([[ -8],
       [-21],
       [-31]])

In [ ]:
np.mean(X[0])

-20.0

In [ ]:
Y[0]

array([-20.])

In [ ]:
# Data partitionning
train_ratio = 0.8
train_size = int(np.floor(n_samples * train_ratio))
X_train = X[:train_size]
Y_train = Y[:train_size]
X_val = X[train_size:]
Y_val = X[train_size:]

In [ ]:
# Model
def layer(n_units, act_func, input):
  weights = np.random.randn(n_units, input.shape[0])
  bias = 0
  Z = np.dot(weights, input) + bias

  if act_func == 'linear':
    return Z
  else : return Z

In [ ]:
# Weights initialization
w = np.random.randn(5,5)
w.shape

(5, 5)